<?php

return [
    // Curated Traditional Chinese names. Unknown names remain in their original
    // language so a machine translation cannot silently identify the wrong team.
    'teams' => [
        'Arizona Diamondbacks' => '亞利桑那響尾蛇', 'Atlanta Braves' => '亞特蘭大勇士',
        'Baltimore Orioles' => '巴爾的摩金鶯', 'Boston Red Sox' => '波士頓紅襪',
        'Chicago Cubs' => '芝加哥小熊', 'Chicago White Sox' => '芝加哥白襪',
        'Cincinnati Reds' => '辛辛那提紅人', 'Cleveland Guardians' => '克里夫蘭守護者',
        'Colorado Rockies' => '科羅拉多落磯', 'Detroit Tigers' => '底特律老虎',
        'Houston Astros' => '休士頓太空人', 'Kansas City Royals' => '堪薩斯市皇家',
        'Los Angeles Angels' => '洛杉磯天使', 'Los Angeles Dodgers' => '洛杉磯道奇',
        'Miami Marlins' => '邁阿密馬林魚', 'Milwaukee Brewers' => '密爾瓦基釀酒人',
        'Minnesota Twins' => '明尼蘇達雙城', 'New York Mets' => '紐約大都會',
        'New York Yankees' => '紐約洋基', 'Athletics' => '運動家',
        'Oakland Athletics' => '運動家', 'Sacramento Athletics' => '運動家',
        'Philadelphia Phillies' => '費城費城人', 'Pittsburgh Pirates' => '匹茲堡海盜',
        'San Diego Padres' => '聖地牙哥教士', 'San Francisco Giants' => '舊金山巨人',
        'Seattle Mariners' => '西雅圖水手', 'St. Louis Cardinals' => '聖路易紅雀',
        'St Louis Cardinals' => '聖路易紅雀', 'Tampa Bay Rays' => '坦帕灣光芒',
        'Texas Rangers' => '德州遊騎兵', 'Toronto Blue Jays' => '多倫多藍鳥',
        'Washington Nationals' => '華盛頓國民',

        'Atlanta Hawks' => '亞特蘭大老鷹', 'Boston Celtics' => '波士頓塞爾提克',
        'Brooklyn Nets' => '布魯克林籃網', 'Charlotte Hornets' => '夏洛特黃蜂',
        'Chicago Bulls' => '芝加哥公牛', 'Cleveland Cavaliers' => '克里夫蘭騎士',
        'Dallas Mavericks' => '達拉斯獨行俠', 'Denver Nuggets' => '丹佛金塊',
        'Detroit Pistons' => '底特律活塞', 'Golden State Warriors' => '金州勇士',
        'Houston Rockets' => '休士頓火箭', 'Indiana Pacers' => '印第安納溜馬',
        'Los Angeles Clippers' => '洛杉磯快艇', 'LA Clippers' => '洛杉磯快艇',
        'Los Angeles Lakers' => '洛杉磯湖人', 'Memphis Grizzlies' => '曼菲斯灰熊',
        'Miami Heat' => '邁阿密熱火', 'Milwaukee Bucks' => '密爾瓦基公鹿',
        'Minnesota Timberwolves' => '明尼蘇達灰狼', 'New Orleans Pelicans' => '紐奧良鵜鶘',
        'New York Knicks' => '紐約尼克', 'Oklahoma City Thunder' => '奧克拉荷馬雷霆',
        'Orlando Magic' => '奧蘭多魔術', 'Philadelphia 76ers' => '費城七六人',
        'Phoenix Suns' => '鳳凰城太陽', 'Portland Trail Blazers' => '波特蘭拓荒者',
        'Sacramento Kings' => '沙加緬度國王', 'San Antonio Spurs' => '聖安東尼奧馬刺',
        'Toronto Raptors' => '多倫多暴龍', 'Utah Jazz' => '猶他爵士',
        'Washington Wizards' => '華盛頓巫師',

        'Arizona Cardinals' => '亞利桑那紅雀', 'Atlanta Falcons' => '亞特蘭大獵鷹',
        'Baltimore Ravens' => '巴爾的摩烏鴉', 'Buffalo Bills' => '水牛城比爾',
        'Carolina Panthers' => '卡羅萊納黑豹', 'Chicago Bears' => '芝加哥熊',
        'Cincinnati Bengals' => '辛辛那提孟加拉虎', 'Cleveland Browns' => '克里夫蘭布朗',
        'Dallas Cowboys' => '達拉斯牛仔', 'Denver Broncos' => '丹佛野馬',
        'Detroit Lions' => '底特律雄獅', 'Green Bay Packers' => '綠灣包裝工',
        'Houston Texans' => '休士頓德州人', 'Indianapolis Colts' => '印第安納波利斯小馬',
        'Jacksonville Jaguars' => '傑克遜維爾美洲虎', 'Kansas City Chiefs' => '堪薩斯市酋長',
        'Las Vegas Raiders' => '拉斯維加斯突襲者', 'Los Angeles Chargers' => '洛杉磯電光',
        'Los Angeles Rams' => '洛杉磯公羊', 'Miami Dolphins' => '邁阿密海豚',
        'Minnesota Vikings' => '明尼蘇達維京人', 'New England Patriots' => '新英格蘭愛國者',
        'New Orleans Saints' => '紐奧良聖徒', 'New York Giants' => '紐約巨人',
        'New York Jets' => '紐約噴射機', 'Philadelphia Eagles' => '費城老鷹',
        'Pittsburgh Steelers' => '匹茲堡鋼人', 'San Francisco 49ers' => '舊金山四九人',
        'Seattle Seahawks' => '西雅圖海鷹', 'Tampa Bay Buccaneers' => '坦帕灣海盜',
        'Tennessee Titans' => '田納西泰坦', 'Washington Commanders' => '華盛頓指揮官',

        'Anaheim Ducks' => '安那翰鴨', 'Boston Bruins' => '波士頓棕熊',
        'Buffalo Sabres' => '水牛城軍刀', 'Calgary Flames' => '卡加利火焰',
        'Carolina Hurricanes' => '卡羅萊納颶風', 'Chicago Blackhawks' => '芝加哥黑鷹',
        'Colorado Avalanche' => '科羅拉多雪崩', 'Columbus Blue Jackets' => '哥倫布藍衣',
        'Dallas Stars' => '達拉斯星', 'Detroit Red Wings' => '底特律紅翼',
        'Edmonton Oilers' => '艾德蒙頓油人', 'Florida Panthers' => '佛羅里達美洲豹',
        'Los Angeles Kings' => '洛杉磯國王', 'Minnesota Wild' => '明尼蘇達狂野',
        'Montreal Canadiens' => '蒙特婁加拿大人', 'Montréal Canadiens' => '蒙特婁加拿大人',
        'Nashville Predators' => '納許維爾掠奪者', 'New Jersey Devils' => '紐澤西魔鬼',
        'New York Islanders' => '紐約島人', 'New York Rangers' => '紐約遊騎兵',
        'Ottawa Senators' => '渥太華參議員', 'Philadelphia Flyers' => '費城飛人',
        'Pittsburgh Penguins' => '匹茲堡企鵝', 'San Jose Sharks' => '聖荷西鯊魚',
        'Seattle Kraken' => '西雅圖海怪', 'St. Louis Blues' => '聖路易藍調',
        'Tampa Bay Lightning' => '坦帕灣閃電', 'Toronto Maple Leafs' => '多倫多楓葉',
        'Utah Mammoth' => '猶他猛獁', 'Vancouver Canucks' => '溫哥華加人',
        'Vegas Golden Knights' => '維加斯黃金騎士', 'Washington Capitals' => '華盛頓首都',
        'Winnipeg Jets' => '溫尼伯噴射機',

        'Arsenal' => '兵工廠', 'Aston Villa' => '阿斯頓維拉',
        'AFC Bournemouth' => '伯恩茅斯', 'Bournemouth' => '伯恩茅斯',
        'Brentford' => '布倫特福德', 'Brighton & Hove Albion' => '布萊頓',
        'Chelsea' => '切爾西', 'Crystal Palace' => '水晶宮', 'Everton' => '艾佛頓',
        'Fulham' => '富勒姆', 'Ipswich Town' => '伊普斯維奇', 'Leeds United' => '里茲聯',
        'Leicester City' => '萊斯特城', 'Liverpool' => '利物浦',
        'Manchester City' => '曼城', 'Manchester United' => '曼聯',
        'Newcastle United' => '紐卡索聯', 'Nottingham Forest' => '諾丁漢森林',
        'Southampton' => '南安普敦', 'Sunderland' => '桑德蘭',
        'Tottenham Hotspur' => '托特納姆熱刺', 'West Ham United' => '西漢姆聯',
        'Wolverhampton Wanderers' => '狼隊', 'Real Madrid' => '皇家馬德里',
        'Barcelona' => '巴塞隆納', 'Bayern Munich' => '拜仁慕尼黑',
        'Paris Saint-Germain' => '巴黎聖日耳曼', 'Inter Milan' => '國際米蘭',
        'AC Milan' => 'AC 米蘭', 'Juventus' => '尤文圖斯',

        'Spain' => '西班牙', 'Czechia' => '捷克', 'Czech Republic' => '捷克',
        'North Macedonia' => '北馬其頓', 'Scotland' => '蘇格蘭',
        'Switzerland' => '瑞士', 'Slovenia' => '斯洛維尼亞',
        'USA' => '美國', 'United States' => '美國', 'Mexico' => '墨西哥',
        'Azerbaijan' => '亞塞拜然', 'Lithuania' => '立陶宛',
        'Malta' => '馬爾他', 'Andorra' => '安道爾', 'Kosovo' => '科索沃',
        'Austria' => '奧地利', 'Ireland' => '愛爾蘭', 'Israel' => '以色列',
        'Wales' => '威爾斯', 'Denmark' => '丹麥', 'Portugal' => '葡萄牙',
        'Norway' => '挪威', 'Netherlands' => '荷蘭', 'Serbia' => '塞爾維亞',
        'Greece' => '希臘', 'Germany' => '德國', 'England' => '英格蘭',
        'France' => '法國', 'Italy' => '義大利', 'Japan' => '日本',
        'South Korea' => '南韓', 'Taiwan' => '台灣', 'Australia' => '澳洲',
        'Brazil' => '巴西', 'Argentina' => '阿根廷', 'Canada' => '加拿大',

        'Atlanta Dream' => '亞特蘭大夢想', 'New York Liberty' => '紐約自由人',
        'Golden State Valkyries' => '金州女武神', 'Las Vegas Aces' => '拉斯維加斯王牌',
        'South East Melbourne Phoenix' => '東南墨爾本鳳凰',
        'Illawarra Hawks' => '伊拉瓦拉老鷹', 'Adelaide 36ers' => '阿德雷德三十六人',
        'New Zealand Breakers' => '紐西蘭破壞者',
        'Sydney Roosters' => '雪梨公雞', 'Newcastle Knights' => '紐卡索騎士',
        'Montreal Alouettes' => '蒙特婁雲雀', 'Winnipeg Blue Bombers' => '溫尼伯藍轟炸機',
    ],
    'events' => [
        '20th Asian Games' => '第 20 屆亞洲運動會',
        'Formula 1' => 'F1 一級方程式', 'Grand Prix of Japan' => '日本大獎賽',
        'Grand Prix of Indonesia' => '印尼大獎賽', 'Malaysian Grand Prix' => '馬來西亞大獎賽',
        'Bahrain GP' => '巴林大獎賽', 'Singapore GP' => '新加坡大獎賽',
        'World Rally Championship' => '世界拉力錦標賽',
        'Rally Italia Sardegna' => '義大利薩丁尼亞拉力賽',
        'NASCAR Cup Series' => 'NASCAR 杯系列賽',
        'Motocross of Nations' => '世界越野摩托車國家賽',
        "Dana White's Contender Series" => '白大拿挑戰者系列賽',
        'Legacy Fighting Championship' => '傳奇格鬥錦標賽',
        'World Grand Prix' => '世界大獎賽',
    ],
];
